name=PressureSensorLib
version=1.0.1
author=Tunasha,Babatunde Adg
maintainer=Babatunde Adg <tunashapcb@gmail.com>
sentence=Arduino library for interfacing with hydrostatic pressure sensor.
paragraph=Handles voltage and current conversions for 4-20mA or 0-10V pressure transducers. Supports configurable pressure ranges and sample averaging.
category=Sensors
url=https://github.com/Tunasha/PressureSensorLib
architectures=*
includes=PressureSensorLib.h
